# Generated by Django 5.2.1 on 2025-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_done_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2025-05-24', verbose_name='Deadline'),
        ),
    ]
