# Generated by Django 5.2.1 on 2025-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='24-05-2025', verbose_name='Deadline'),
        ),
    ]
