# Generated by Django 5.2.1 on 2025-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2025-05-24', verbose_name='Deadline'),
        ),
    ]
