# Generated by Django 5.2.1 on 2025-06-02 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 6, 2)),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nom'),
        ),
    ]
